ALTER TABLE route_policies
  ADD COLUMN IF NOT EXISTS risk_challenge_score INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS risk_block_score INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS risk_observe_score INTEGER NOT NULL DEFAULT 0;
